### ISSUE TITLE
You can add IdeaPad Slim 5 14AHP9 - Type 83DB

### ISSUE THREAD

**Issue by Broukmiken** [chnzzh/lenovo-logo-changer#2]
Hello,
you can add this laptop to your working devices :
 IdeaPad Slim 5 14AHP9 - Type 83DB
your software works like a charm :)
thanks so much

![vlcsnap-2024-09-14-18h32m12s418](https://github.com/user-attachments/assets/bfacf8b1-b986-4215-a5a1-04c2f5cb1e58)

https://github.com/user-attachments/assets/49340f0a-2970-42e7-bd9e-af91cc0506fc

**Comment by chnzzh** [comment]
Thanks for your test!
I’ll update the tool’s support list.
By the way, your pic looks cool! )
