### ISSUE TITLE
Will it suport another Lenovo Laptop type ?

### ISSUE THREAD

**Issue by Teknisi-Anime** [chnzzh/lenovo-logo-changer#4]
I want to change my boot logo on my Lenovo LOQ 15irh8, but most of the tools I found are only for Thinkpad or Ideapad series. Can this tool work other than the series you mentioned?

**Comment by chnzzh** [comment]
Yes, this tool should work with most of Lenovo's laptop series released in recent years.The list I provided includes only the models that I've verified (or others have verified).

Btw, this tool will automatically check if the device is supported, it will display **Your device is supported** if it is. If you're unsure whether your model is supported, you can simply run this tool and see what it displays.

**Comment by Teknisi-Anime** [comment]
I have tried it but it turns into windows 11 logo instead of the image I input into the program. My logo format is png

**Comment by Teknisi-Anime** [comment]
Ok that works, maybe you can add a note not to use the file as logo 1 - 4 because that was my initial file name and it got changed to windows 11 logo

Oh yea, You can also add Lenovo LOQ 15IRH8 to the list.

Here the footage of the test 

Uploading VID20241230021749.mp4…
